services:
  web:
    build: ./backend
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env 
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./backend/.env 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:

